### ISSUE TITLE
During migration Foreigher throw NoMethodError

### ISSUE THREAD

**Issue by Draqun** [matthuhiggins/foreigner#155]
Hi.

I tried use a Foreigner into my project. And it throw me a NoMethodError (http://pastebin.com/cZBiBUwZ - stacktrace). I try it with ruby 1.9, 2.0 and 2.1 and PostgreSQL 9.1.14 and i have all the times this same error.

My code for create database

```
  class CreateAuthors < ActiveRecord::Migration
  def change
    create_table :authors do |t|
      t.string :name
      t.timestamps null: false
    end
  end
end



  class CreateStores < ActiveRecord::Migration
  def change
    create_table :stores do |t|
      t.string :name
      t.timestamps null: false
    end
  end
end

  class CreateBooks < ActiveRecord::Migration
  def change
  create_table :books do |t|
    t.string :title
    t.integer :store_id
    t.foreign_key :stores, dependent: :delete
    t.integer :author_id
    t.foreign_key :authors, dependent: :delete
    t.timestamps null: false
  end
  #add_foreign_key(:books, :stores, dependent: :delete)
  #add_foreign_key(:books, :authors, dependent: :delete)
end
end
```

Why it throw a error?

**Comment by guiman** [comment]
I believe this issue is not completely related to 4.2.0 itself and the new foreign key support but this other one I've been working on https://github.com/matthuhiggins/foreigner/issues/161

**Comment by Mehonoshin** [comment]
Hi!

I'm having the same issue with Rails 4.2.0 and Foreigner 1.7.2

**Comment by john-999** [comment]
+ 1

**Comment by matthuhiggins** [comment]
I have no plans to support foreigner for Rails 4.2 and after.

I could say "don't use foreigner if you are on Rails 4.2". If someone wants to make foreigner work with Rails 4.2, you are welcome to.

**Comment by jcoyne** [comment]
@matthuhiggins Thanks for clearing that up!
