### ISSUE TITLE
Readme addition: plans for rails 4.2 onwards

### ISSUE THREAD

**Issue by nruth** [matthuhiggins/foreigner#167]
First of all thank you for providing this wonderful gem. It's saved us from a lot of bugs and data corruption in production.

Now that rails has taken a distributed systems class it'd be great to have some guidance on whether we should transition away: what we'll lose, whether support will continue.

A note in the readme about future plans would be enough.

**Comment by PikachuEXE** [comment]
:+1:

**Comment by pscdodd** [comment]
With Rails 4.2 I get the following error from "rake db:schema:dump":

rake aborted!
NoMethodError: undefined method `column' for #<Foreigner::ConnectionAdapters::ForeignKeyDefinition:0x000000044d1b20>

**Comment by joker-777** [comment]
:+1:

**Comment by matthuhiggins** [comment]
See #178
